# 运行的环境是custom，表示是一个docker的环境，会主动找docker file；
runtime: custom
# flexible environment: auto-scaling; 对于customization支持地更好一些;
# 会自己创建一些VM跑;
env: flex
network:
  name: default
  subnetwork_name: default
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
